mchat/blueprints/auth.py
from flask import render_template,flash,redirect,url_for,Blueprint,request
from flask_login import login_user,logout_user,login_required,current_user

from mchat.extensions import db
from mchat.models import User

auth_bp=Blueprint('auth',__name__)

@auth_bp.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('chat.home'))

    if request.method=='POST':
        email=request.form['email']
        password=request.form['password']
        remember_me=request.form.get('remember',False)

        if remember_me:
            remember_me=True

        user=User.query.filter_by(email=email).first()

        if user is not None:
            if user.password_hash is None:
                flash('Please use the third party service to log in.')
                return redirect(url_for('.login'))
            if user.verify_password(password):
                login_user(user,remember_me)
                return redirect(url_for('chat.home'))

        flash('Email or password is incorrect.')
        return redirect(url_for('.login'))

    return render_template('auth/login.html')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('chat.home'))


@auth_bp.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    if request.method=='POST':
        email=request.form['email'].lower()

        user=User.query.filter_by(email=email).first()
        if user is not None:
            flash('Email is already registered,please log in.')
            return redirect(url_for('.login'))

        nickname=request.form['nickname']
        password=request.form['password']

        user=User(nickname=nickname,email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        login_user(user,remember=True)
        return redirect(url_for('chat.profile'))
    return render_template('auth/register.html')

mchat/blueprints/chat.py
from flask import render_template,redirect,url_for,Blueprint,request,current_app
from flask_login import current_user,login_required
from flask_socketio import emit

from mchat.extensions import socketio,db
from mchat.forms import ProfileForm
from mchat.models import Message,User
from mchat.utils import flash_errors,to_html

chat_bp=Blueprint('chat',__name__)

online_users=[]

@socketio.on('new message')
def new_message(message_body):
    html_message=to_html(message_body)
    message=Message(author=current_user._get_current_object(),body=html_message)
    db.session.add(message)
    db.session.commit()
    emit('new message',
         {'message_html':render_template('chat/_message.html',message=message),
          'message_body':html_message,
          'gravatar':current_user.gravatar,
          'nickname':current_user.nickname,
          'user_id':current_user.id
          },
         broadcast=True)

@socketio.on('new message',namespace='/anonymous')
def new_anonymous_message(message_body):
    html_message=to_html(message_body)
    avatar='https://www.gravatar.com/avatar?d=mm'
    nickname='Anonymous'
    emit('new message',
         {'message_html':render_template(
             'chat/_anonymous_message.html',
             message=html_message,
             avatar=avatar,
             nickname=nickname
         ),
             'message_body': html_message,
             'gravatar': current_user.gravatar,
             'nickname': current_user.nickname,
             'user_id': current_user.id
         },broadcast=True,namespace='/anonymous')

@socketio.on('connect')
def connect():
    global online_users
    if current_user.is_authenticated and current_user.id not in online_users:
        online_users.append(current_user.id)
    emit('user count',{'count':len(online_users)},broadcast=True)


@socketio.on('disconnect')
def disconnect():
    global online_users
    if current_user.is_authenticated and current_user.id in online_users:
        online_users.remove(current_user.id)
    emit('user count',{'count':len(online_users)},broadcast=True)


@chat_bp.route('/')
def home():
    amount=current_app.config['MESSAGE_PER_PAGE']
    messages=Message.query.order_by(Message.timestamp.asc())[-amount:]
    user_amount=User.query.count()
    return render_template('chat/home.html',messages=messages,user_amount=user_amount)


@chat_bp.route('/profile',methods=['GET','POST'])
@login_required
def profile():
    form=ProfileForm()
    if form.validate_on_submit():
        current_user.nickname=form.nickname.data
        current_user.github=form.github.data
        current_user.website=form.website.data
        current_user.bio=form.bio.data
        db.session.commit()
        return redirect(url_for('.home'))
    flash_errors(form)
    return render_template('chat/profile.html',form=form)

@chat_bp.route('/profile/<user_id>')
def get_profile(user_id):
    user=User.query.get_or_404(user_id)
    return render_template('chat/_profile_card.html',user=user)

@chat_bp.route('/anonymous')
def anonymous():
    return render_template('chat/anonymous.html')

@chat_bp.route('/messages')
def get_messages():
    page=request.args.get('page',1,type=int)
    pagination=Message.query.order_by(Message.timestamp.desc()).paginate(
        page,per_page=current_app.config['MESSAGE_PER_PAGE']
    )
    messages=pagination.items
    return render_template('chat/_messages.html',messages=messages[::-1])

mchat/templates/chat/_anonymous_message.html
<div class="msg-box">

    <div class="picture"><img src="{{ avatar }}"></div>

    <div class="msg">

        <span class="nickname">{{ nickname }}</span>

        <span class="message-body">{{ message|safe }}</span>

    </div>

    {% if current_user.is_authenticated %}

        <div class="ui icon left center pointing dropdown ellipsis-icon">

            <i class="ellipsis horizontal icon"></i>

            <div class="menu" data-offset="-33">

                <div class="item quote-button"><i class="quote left icon"></i> Quote</div>

            </div>

        </div>

    {% endif %}
</div>

mchat/templates/chat/_message.html
<div class="msg-box">

    <div class="picture">

        <img class="pop-card" data-position="right center" data-offset="-40"

             data-href="{{ url_for('chat.get_profile', user_id=message.author.id) }}"

             src="{{ message.author.gravatar }}">

    </div>

    <div class="msg">

        <span class="nickname">{{ message.author.nickname }}</span>

        <small class="timestamp">{{ moment(message.timestamp).format('lll') }}</small>

        <span class="message-body">{{ message.body|safe }}</span>

    </div>

    {% if current_user.is_authenticated %}

        <div class="ui icon left center pointing dropdown ellipsis-icon">

            <i class="ellipsis horizontal icon"></i>

            <div class="menu" data-offset="-33">

                <div class="item quote-button"><i class="quote left icon"></i> Quote</div>

            </div>

        </div>

    {% endif %}

</div>

mchat/templates/chat/_messages.html
{% for message in messages %}

    {% include "chat/_message.html" %}

{% endfor %}

mchat/templates/chat/_profile_card.html
<div class="ui items profile-card">

    <div class="item">

        <div class="ui tiny image">

            <img src="{{ user.gravatar }}">

        </div>

        <div class="content">

            <div class="header">{{ user.nickname }}</div>

            <div class="description">{{ user.bio or 'This user want to maintain an aura of mystique.' }}</div>

        </div>

    </div>

    {% if user.github %}

        <i class="github icon"></i><a href="{{ user.github }}" target="_blank">Github</a>

    {% endif %}

    {% if user.website %}

        <i class="linkify icon"></i><a href="{{ user.website }}" target="_blank">Website</a>

    {% endif %}

</div>

mchat/templates/chat/anonymous.html
{% extends 'base.html' %}


{% block page_title %}Incognito{% endblock %}


{% block nav %}

    <div class="ui top fixed borderless menu">

        <a class="item mchat" href="{{ url_for('chat.home') }}" title="Go Back">

            <img src="{{ url_for('static', filename='2.jpg') }}">

            <span>Mchat (Incognito Mode)</span>

        </a>

        <div class="right menu hide-on-mobile">

            {% if not current_user.is_authenticated %}

                <div class="item">

                    <a class="ui primary button" href="{{ url_for('auth.login') }}">

                        Sign in</a>

                </div>

            {% endif %}

        </div>

    </div>

{% endblock %}


{% block content %}

    <div class="pusher">

        <div class="chat-box">

            <div class="messages"></div>

        </div>

        <div class="input-area">

            <div class="ui grid form">

                <div class="ten wide column">

                    <div class="field fluid message-box">

                        {% if current_user.is_authenticated %}

                            <img class="input-avatar" src="https://www.gravatar.com/avatar?d=mm">

                            <textarea rows="2" id="message-textarea"

                                      placeholder="Write your message here... Enter to send"></textarea>

                        {% else %}

                            <div class="ui floating message">Please <a href="{{ url_for('auth.login') }}">Sign in</a> or

                                <a

                                        href="{{ url_for('auth.register') }}">Sign up</a> to send message.

                            </div>

                        {% endif %}

                    </div>

                </div>

            </div>

        </div>

    </div>

{% endblock %}


{% block scripts %}

    {{ super() }}

    <script type="text/javascript">

        var socket = io('/anonymous');

    </script>

{% endblock %}

mchat/templates/chat/home.html
{% extends 'base.html' %}

{% block title %}MChat{% endblock %}



{% block content %}

    <div class="pusher">

        <div class="chat-box">

            <div class="messages">
                <div class="ui text loader">Loading...</div>

                {% include 'chat/_messages.html' %}

            </div>

        </div>

        <div class="input-area">

            <div class="ui grid form">

                <div class="ten wide column">

                    <div class="field fluid message-box">

                        {% if current_user.is_authenticated %}

                            <img class="pop-card input-avatar" data-position="bottom left"

                                 data-href="{{ url_for('chat.get_profile', user_id=current_user.id) }}"

                                 src="{{ current_user.gravatar }}">

                            <textarea rows="2" id="message-textarea"

                                      placeholder="Write your message here... Enter to send"></textarea>

                        {% else %}

                            <div class="ui floating message">Please <a href="{{ url_for('auth.login') }}">Sign in</a> or

                                <a href="{{ url_for('auth.register') }}">Sign up</a> to send message.

                            </div>

                        {% endif %}

                    </div>

                </div>

            </div>

        </div>

    </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        var socket=io('/');
    </script>

{% endblock %}

mchat/templates/chat/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <div class="ui attached message">
                <div class="header ui image ">
                    <img src="{{ url_for('static', filename='2.jpg') }}" class="image">
                    <div class="content">Tell us about you!</div>
                </div>
            </div>
            <form class="profile ui form attached left aligned fluid segment" method="post"
                  action="{{ url_for('chat.profile') }}">
                <div class="field eight wide">
                    <label>Nickname</label>
                    <input name="nickname" placeholder="Nickname" type="text" value="{{ current_user.nickname }}">
                </div>
                <div class="field">
                    <label>Github</label>
                    <input name="github" placeholder="https://github.com/greyli" type="text"
                           value="{{ current_user.github or '' }}">
                </div>
                <div class="field">
                    <label>Website</label>
                    <input name="website" placeholder="http://greyli.com" type="text"
                           value="{{ current_user.website or '' }}">
                </div>
                <div class="field">
                    <label>Bio</label>
                    <input name="bio" placeholder="I'm a ..." type="text" value="{{ current_user.bio or '' }}">
                </div>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <div class="fields two">
                    <div class="ui orange submit fluid button">Start Chat</div>
                </div>
            </form>
            {% for error_message in get_flashed_messages() %}
                <div class="ui message floating warning closeable">
                    <i class="close icon"></i>
                    <div>{{ error_message }}</div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %} 