mchat/blueprints/auth.py
from flask import render_template,flash,redirect,url_for,Blueprint,request
from flask_login import login_user,logout_user,login_required,current_user

from mchat.extensions import db
from mchat.models import User

auth_bp=Blueprint('auth',__name__)

@auth_bp.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('chat.home'))

    if request.method=='POST':
        email=request.form['email']
        password=request.form['password']
        remember_me=request.form.get('remember',False)

        if remember_me:
            remember_me=True

        user=User.query.filter_by(email=email).first()

        if user is not None:
            if user.password_hash is None:
                flash('Please use the third party service to log in.')
                return redirect(url_for('.login'))
            if user.verify_password(password):
                login_user(user,remember_me)
                return redirect(url_for('chat.home'))

        flash('Email or password is incorrect.')
        return redirect(url_for('.login'))

    return render_template('auth/login.html')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('chat.home'))


@auth_bp.route('/register',methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    if request.method=='POST':
        email=request.form['email'].lower()

        user=User.query.filter_by(email=email).first()
        if user is not None:
            flash('Email is already registered,please log in.')
            return redirect(url_for('.login'))

        nickname=request.form['nickname']
        password=request.form['password']

        user=User(nickname=nickname,email=email)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        login_user(user,remember=True)
        return redirect(url_for('chat.profile'))
    return render_template('auth/register.html')

mchat/blueprints/chat.py
from flask import render_template,redirect,url_for,Blueprint,request,current_app
from flask_login import current_user,login_required
from flask_socketio import emit

from mchat.extensions import socketio,db
from mchat.forms import ProfileForm
from mchat.models import Message,User
from mchat.utils import flash_errors,to_html

chat_bp=Blueprint('chat',__name__)

online_users=[]

@socketio.on('new message')
def new_message(message_body):
    html_message=to_html(message_body)
    message=Message(author=current_user._get_current_object(),body=html_message)
    db.session.add(message)
    db.session.commit()
    emit('new message',
         {'message_html':render_template('chat/_message.html',message=message),
          'message_body':html_message,
          'gravatar':current_user.gravatar,
          'nickname':current_user.nickname,
          'user_id':current_user.id
          },
         broadcast=True)

@socketio.on('new message',namespace='/anonymous')
def new_anonymous_message(message_body):
    html_message=to_html(message_body)
    avatar='https://www.gravatar.com/avatar?d=mm'
    nickname='Anonymous'
    emit('new message',
         {'message_html':render_template(
             'chat/_anonymous_message.html',
             message=html_message,
             avatar=avatar,
             nickname=nickname
         ),
             'message_body': html_message,
             'gravatar': current_user.gravatar,
             'nickname': current_user.nickname,
             'user_id': current_user.id
         },broadcast=True,namespace='/anonymous')

@socketio.on('connect')
def connect():
    global online_users
    if current_user.is_authenticated and current_user.id not in online_users:
        online_users.append(current_user.id)
    emit('user count',{'count':len(online_users)},broadcast=True)


@socketio.on('disconnect')
def disconnect():
    global online_users
    if current_user.is_authenticated and current_user.id in online_users:
        online_users.remove(current_user.id)
    emit('user count',{'count':len(online_users)},broadcast=True)


@chat_bp.route('/')
def home():
    amount=current_app.config['MESSAGE_PER_PAGE']
    messages=Message.query.order_by(Message.timestamp.asc())[-amount:]
    user_amount=User.query.count()
    return render_template('chat/home.html',messages=messages,user_amount=user_amount)


@chat_bp.route('/profile',methods=['GET','POST'])
@login_required
def profile():
    form=ProfileForm()
    if form.validate_on_submit():
        current_user.nickname=form.nickname.data
        current_user.github=form.github.data
        current_user.website=form.website.data
        current_user.bio=form.bio.data
        db.session.commit()
        return redirect(url_for('.home'))
    flash_errors(form)
    return render_template('chat/profile.html',form=form)

@chat_bp.route('/profile/<user_id>')
def get_profile(user_id):
    user=User.query.get_or_404(user_id)
    return render_template('chat/_profile_card.html',user=user)

@chat_bp.route('/anonymous')
def anonymous():
    return render_template('chat/anonymous.html')

@chat_bp.route('/messages')
def get_messages():
    page=request.args.get('page',1,type=int)
    pagination=Message.query.order_by(Message.timestamp.desc()).paginate(
        page,per_page=current_app.config['MESSAGE_PER_PAGE']
    )
    messages=pagination.items
    return render_template('chat/_messages.html',messages=messages[::-1])

mchat/templates/base.html
<html>

<head>

    {% block head %}

        <title>{% block title %}{% block page_title %}{% endblock %} - Mchat{% endblock %}</title>

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

        <link rel="stylesheet" href="{{ url_for('static', filename='semantic-ui/semantic.min.css') }}">

    {% endblock %}

</head>

<body>


<div class="ui labeled icon right vertical inverted demo menu sidebar">

    <a class="item" href="{{ url_for('chat.anonymous') }}">

        <i class="user secret icon"></i>

        Incognito Mode

    </a>

    <a class="item" href="https://github.com/markxvii" target="_blank">

        <i class="github icon"></i>

        GitHub

    </a>

    {% if current_user.is_authenticated %}

        <a class="item" href="{{ url_for('chat.profile') }}">

            <i class="setting icon"></i>

            Profile

        </a>

    {% endif %}

    <a class="item" id="show-help-modal">

        <i class="help icon"></i>

        Help

    </a>

    {% if current_user.is_authenticated %}

        <a class="item" href="{{ url_for('auth.logout') }}">

            <i class="power off icon"></i>

            Sign out</a>

    {% endif %}

</div>



{% block nav %}

    <div class="ui top fixed borderless menu">

        <a class="item mchat" href="{{ url_for('chat.home') }}">

            <img src="{{ url_for('static', filename='2.jpg') }}">

            <span>Mchat</span>

        </a>

        <div class="item">

            <div class="ui label black basic" title="Online users">

                <i class="user icon"></i> <span id="user-count">0</span> / {{ user_amount }}

            </div>

        </div>

        <div class="right menu hide-on-mobile">

            {% if not current_user.is_authenticated %}

                <div class="item">

                    <a class="ui primary button" href="{{ url_for('auth.login') }}">

                        Sign in</a>

                </div>

            {% endif %}

            <a class="item" id="toggle-sidebar">

                <i class="sidebar icon"></i>

            </a>

        </div>

    </div>

{% endblock %}



<!-- Help Modal -->

<div class="ui modal small help">

    <div class="header">Markdown Help</div>

    <div class="content">

        <section class="modal--default__content" id="modal-body-region">

            <div>

                <div class="modal-content">

                    <table class="ui celled striped table">

                        <tbody>

                        <tr>

                            <td><strong>Bold</strong></td>

                            <td>**bold**</td>

                        </tr>

                        <tr>

                            <td><i>Italics</i></td>

                            <td>*italics*</td>

                        </tr>

                        <tr>

                            <td>Header</td>

                            <td># H1 ## H2 ### H3</td>

                        </tr>

                        <tr>

                            <td>

                                <li>item</li>

                            </td>

                            <td>* item</td>

                        </tr>

                        <tr>

                            <td>Blockquote</td>

                            <td>&gt; blockquote</td>

                        </tr>

                        <tr>

                            <td><a href="http://greyli.com" target="_blank">Link</a></td>

                            <td>[title](http://...)</td>

                        </tr>

                        <tr>

                            <td>Image</td>

                            <td>![alt](http://...)</td>

                        </tr>

                        <tr>

                            <td><code>code</code></td>

                            <td>`code`</td>

                        </tr>

                        <tr>

                            <td>

                                <div class="codehilite"><pre><span></span><span class="k">def</span> <span class="nf">hello</span><span

                                        class="p">():</span>

    <span class="k">return</span> <span class="s2">"Hello World"</span>

</pre>

                                </div>

                            </td>

                            <td style="line-height: 100%">```python <i style="color: rgba(0,0,0,0.5)">(shift+enter for

                                line

                                break)</i><br>def hello():<br>

                                &nbsp;&nbsp;&nbsp;&nbsp;return "Hello World"<br>```

                            </td>

                        </tr>

                        </tbody>

                    </table>

                </div>

                <br>

            </div>

        </section>

    </div>

    <div class="actions">

        <button class="ui button cancel">Close</button>

    </div>

</div>




<!-- Mobile message Modal -->

<div id="mobile-new-message-modal" class="ui modal small">

    <div class="content">

        <div class="ui form">

            <textarea id="mobile-message-textarea" rows="15"></textarea>

        </div>

    </div>

    <div class="actions">

        <button class="ui button cancel">Cancel</button>

        <button class="ui button orange approve" id="send-button">Send</button>

    </div>

</div>


{% block content %}{% endblock %}

{% block scripts %}

    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>

    <script src="{{ url_for('static', filename='semantic-ui/semantic.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/socket.io.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/forms.js') }}"></script>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}

    <script type="text/javascript">

        var root_url = "{{ url_for('chat.home') }}";

        var messages_url = "{{ url_for('chat.get_messages') }}";

        var current_user_id = {{ current_user.id|default(0) }};

        var csrf_token = "{{ csrf_token() }}";

    </script>

{% endblock %}

</body>

</html>

mchat/templates/error.html
{% extends 'base.html' %}
{% block title %}{{ code }} Error{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <div class="ui attached message">
                <div class="header ui image ">
                    <img src="{{ url_for('static', filename='2.jpg') }}" class="image">
                    <div class="content">
                        <span class="mchat-text">Mchat</span> - {{ code }}
                    </div>
                </div>
                <p>{{ description }}</p>
                <a class="icon" href="{{ url_for('chat.home') }}">Return Home</a>
            </div>
        </div>
    </div>
{% endblock %} 